-- OPTIONAL hardening — government-ids storage deny policies.
--
-- The government-ids bucket is private, written via service-role, and read
-- exclusively through 60s signed URLs, so no storage.objects policy is
-- required for the threat model. Run this ONLY when you want explicit deny
-- policies anyway. storage.objects is owned by supabase_storage_admin (NOT
-- the postgres role the SQL editor runs as), so it must run under that owner:
--
--   set role supabase_storage_admin;
--   alter table storage.objects enable row level security;
--   create policy government_ids_service_role_all on storage.objects
--     for all to service_role using (bucket_id = 'government-ids')
--     with check (bucket_id = 'government-ids');
--   create policy government_ids_no_anon_read on storage.objects
--     for select to anon using (false);
--   create policy government_ids_no_public_read on storage.objects
--     for select to authenticated using (false);
--   reset role;
--
-- To remove later: drop policy government_ids_service_role_all on storage.objects;
-- drop policy government_ids_no_anon_read on storage.objects;
-- drop policy government_ids_no_public_read on storage.objects;
