-- Countries master data — ISO 3166-1 alpha-2 canonical reference
-- E-31 Country (config). Reference for location verification, member profile, public config.
-- No bounding boxes / polygons / coordinate logic — provider resolves country, this table validates/identifies.
-- Follows existing RLS pattern (cms_contents): public read (anon, authenticated), service_role write.

create table if not exists public.countries (
  code char(2) primary key check (code ~ '^[A-Z]{2}$'),
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep updated_at in sync
create or replace function public.countries_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists countries_updated_at on public.countries;
create trigger countries_updated_at
  before update on public.countries
  for each row execute function public.countries_set_updated_at();

-- RLS
alter table public.countries enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='countries' and policyname='countries_read_all') then
    create policy countries_read_all on public.countries for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='countries' and policyname='countries_service_all') then
    create policy countries_service_all on public.countries for all to service_role using (true) with check (true);
  end if;
end $$;

-- Indexes
create index if not exists countries_is_active_idx on public.countries (is_active) where is_active = true;

-- Seed — ISO 3166-1 alpha-2 official names. Idempotent via ON CONFLICT.
insert into public.countries (code, name, is_active) values
  ('AF','Afghanistan',true),
  ('AL','Albania',true),
  ('DZ','Algeria',true),
  ('AS','American Samoa',true),
  ('AD','Andorra',true),
  ('AO','Angola',true),
  ('AI','Anguilla',true),
  ('AQ','Antarctica',true),
  ('AG','Antigua and Barbuda',true),
  ('AR','Argentina',true),
  ('AM','Armenia',true),
  ('AW','Aruba',true),
  ('AU','Australia',true),
  ('AT','Austria',true),
  ('AZ','Azerbaijan',true),
  ('BS','Bahamas',true),
  ('BH','Bahrain',true),
  ('BD','Bangladesh',true),
  ('BB','Barbados',true),
  ('BY','Belarus',true),
  ('BE','Belgium',true),
  ('BZ','Belize',true),
  ('BJ','Benin',true),
  ('BM','Bermuda',true),
  ('BT','Bhutan',true),
  ('BO','Bolivia (Plurinational State of)',true),
  ('BQ','Bonaire, Sint Eustatius and Saba',true),
  ('BA','Bosnia and Herzegovina',true),
  ('BW','Botswana',true),
  ('BV','Bouvet Island',true),
  ('BR','Brazil',true),
  ('IO','British Indian Ocean Territory',true),
  ('BN','Brunei Darussalam',true),
  ('BG','Bulgaria',true),
  ('BF','Burkina Faso',true),
  ('BI','Burundi',true),
  ('CV','Cabo Verde',true),
  ('KH','Cambodia',true),
  ('CM','Cameroon',true),
  ('CA','Canada',true),
  ('KY','Cayman Islands',true),
  ('CF','Central African Republic',true),
  ('TD','Chad',true),
  ('CL','Chile',true),
  ('CN','China',true),
  ('CX','Christmas Island',true),
  ('CC','Cocos (Keeling) Islands',true),
  ('CO','Colombia',true),
  ('KM','Comoros',true),
  ('CG','Congo',true),
  ('CD','Congo, Democratic Republic of the',true),
  ('CK','Cook Islands',true),
  ('CR','Costa Rica',true),
  ('HR','Croatia',true),
  ('CU','Cuba',true),
  ('CW','Curaçao',true),
  ('CY','Cyprus',true),
  ('CZ','Czechia',true),
  ('DK','Denmark',true),
  ('DJ','Djibouti',true),
  ('DM','Dominica',true),
  ('DO','Dominican Republic',true),
  ('EC','Ecuador',true),
  ('EG','Egypt',true),
  ('SV','El Salvador',true),
  ('GQ','Equatorial Guinea',true),
  ('ER','Eritrea',true),
  ('EE','Estonia',true),
  ('SZ','Eswatini',true),
  ('ET','Ethiopia',true),
  ('FK','Falkland Islands (Malvinas)',true),
  ('FO','Faroe Islands',true),
  ('FJ','Fiji',true),
  ('FI','Finland',true),
  ('FR','France',true),
  ('GF','French Guiana',true),
  ('PF','French Polynesia',true),
  ('TF','French Southern Territories',true),
  ('GA','Gabon',true),
  ('GM','Gambia',true),
  ('GE','Georgia',true),
  ('DE','Germany',true),
  ('GH','Ghana',true),
  ('GI','Gibraltar',true),
  ('GR','Greece',true),
  ('GL','Greenland',true),
  ('GD','Grenada',true),
  ('GP','Guadeloupe',true),
  ('GU','Guam',true),
  ('GT','Guatemala',true),
  ('GG','Guernsey',true),
  ('GN','Guinea',true),
  ('GW','Guinea-Bissau',true),
  ('GY','Guyana',true),
  ('HT','Haiti',true),
  ('HM','Heard Island and McDonald Islands',true),
  ('VA','Holy See',true),
  ('HN','Honduras',true),
  ('HK','Hong Kong',true),
  ('HU','Hungary',true),
  ('IS','Iceland',true),
  ('IN','India',true),
  ('ID','Indonesia',true),
  ('IR','Iran (Islamic Republic of)',true),
  ('IQ','Iraq',true),
  ('IE','Ireland',true),
  ('IM','Isle of Man',true),
  ('IL','Israel',true),
  ('IT','Italy',true),
  ('JM','Jamaica',true),
  ('JP','Japan',true),
  ('JE','Jersey',true),
  ('JO','Jordan',true),
  ('KZ','Kazakhstan',true),
  ('KE','Kenya',true),
  ('KI','Kiribati',true),
  ('KP','Korea (Democratic People''s Republic of)',true),
  ('KR','Korea, Republic of',true),
  ('KW','Kuwait',true),
  ('KG','Kyrgyzstan',true),
  ('LA','Lao People''s Democratic Republic',true),
  ('LV','Latvia',true),
  ('LB','Lebanon',true),
  ('LS','Lesotho',true),
  ('LR','Liberia',true),
  ('LY','Libya',true),
  ('LI','Liechtenstein',true),
  ('LT','Lithuania',true),
  ('LU','Luxembourg',true),
  ('MO','Macao',true),
  ('MG','Madagascar',true),
  ('MW','Malawi',true),
  ('MY','Malaysia',true),
  ('MV','Maldives',true),
  ('ML','Mali',true),
  ('MT','Malta',true),
  ('MH','Marshall Islands',true),
  ('MQ','Martinique',true),
  ('MR','Mauritania',true),
  ('MU','Mauritius',true),
  ('YT','Mayotte',true),
  ('MX','Mexico',true),
  ('FM','Micronesia (Federated States of)',true),
  ('MD','Moldova, Republic of',true),
  ('MC','Monaco',true),
  ('MN','Mongolia',true),
  ('ME','Montenegro',true),
  ('MS','Montserrat',true),
  ('MA','Morocco',true),
  ('MZ','Mozambique',true),
  ('MM','Myanmar',true),
  ('NA','Namibia',true),
  ('NR','Nauru',true),
  ('NP','Nepal',true),
  ('NL','Netherlands',true),
  ('NC','New Caledonia',true),
  ('NZ','New Zealand',true),
  ('NI','Nicaragua',true),
  ('NE','Niger',true),
  ('NG','Nigeria',true),
  ('NU','Niue',true),
  ('NF','Norfolk Island',true),
  ('MK','North Macedonia',true),
  ('MP','Northern Mariana Islands',true),
  ('NO','Norway',true),
  ('OM','Oman',true),
  ('PK','Pakistan',true),
  ('PW','Palau',true),
  ('PS','Palestine, State of',true),
  ('PA','Panama',true),
  ('PG','Papua New Guinea',true),
  ('PY','Paraguay',true),
  ('PE','Peru',true),
  ('PH','Philippines',true),
  ('PN','Pitcairn',true),
  ('PL','Poland',true),
  ('PT','Portugal',true),
  ('PR','Puerto Rico',true),
  ('QA','Qatar',true),
  ('RE','Réunion',true),
  ('RO','Romania',true),
  ('RU','Russian Federation',true),
  ('RW','Rwanda',true),
  ('BL','Saint Barthélemy',true),
  ('SH','Saint Helena, Ascension and Tristan da Cunha',true),
  ('KN','Saint Kitts and Nevis',true),
  ('LC','Saint Lucia',true),
  ('MF','Saint Martin (French part)',true),
  ('PM','Saint Pierre and Miquelon',true),
  ('VC','Saint Vincent and the Grenadines',true),
  ('WS','Samoa',true),
  ('SM','San Marino',true),
  ('ST','Sao Tome and Principe',true),
  ('SA','Saudi Arabia',true),
  ('SN','Senegal',true),
  ('RS','Serbia',true),
  ('SC','Seychelles',true),
  ('SL','Sierra Leone',true),
  ('SG','Singapore',true),
  ('SX','Sint Maarten (Dutch part)',true),
  ('SK','Slovakia',true),
  ('SI','Slovenia',true),
  ('SB','Solomon Islands',true),
  ('SO','Somalia',true),
  ('ZA','South Africa',true),
  ('GS','South Georgia and the South Sandwich Islands',true),
  ('SS','South Sudan',true),
  ('ES','Spain',true),
  ('LK','Sri Lanka',true),
  ('SD','Sudan',true),
  ('SR','Suriname',true),
  ('SJ','Svalbard and Jan Mayen',true),
  ('SE','Sweden',true),
  ('CH','Switzerland',true),
  ('SY','Syrian Arab Republic',true),
  ('TW','Taiwan, Province of China',true),
  ('TJ','Tajikistan',true),
  ('TZ','Tanzania, United Republic of',true),
  ('TH','Thailand',true),
  ('TL','Timor-Leste',true),
  ('TG','Togo',true),
  ('TK','Tokelau',true),
  ('TO','Tonga',true),
  ('TT','Trinidad and Tobago',true),
  ('TN','Tunisia',true),
  ('TR','Türkiye',true),
  ('TM','Turkmenistan',true),
  ('TC','Turks and Caicos Islands',true),
  ('TV','Tuvalu',true),
  ('UG','Uganda',true),
  ('UA','Ukraine',true),
  ('AE','United Arab Emirates',true),
  ('GB','United Kingdom of Great Britain and Northern Ireland',true),
  ('US','United States of America',true),
  ('UM','United States Minor Outlying Islands',true),
  ('UY','Uruguay',true),
  ('UZ','Uzbekistan',true),
  ('VU','Vanuatu',true),
  ('VE','Venezuela (Bolivarian Republic of)',true),
  ('VN','Viet Nam',true),
  ('VG','Virgin Islands (British)',true),
  ('VI','Virgin Islands (U.S.)',true),
  ('WF','Wallis and Futuna',true),
  ('EH','Western Sahara',true),
  ('YE','Yemen',true),
  ('ZM','Zambia',true),
  ('ZW','Zimbabwe',true)
on conflict (code) do update set name = excluded.name, is_active = excluded.is_active, updated_at = now();

comment on table public.countries is 'ISO 3166-1 alpha-2 master data. Validates reverse-geocoded country codes. Not for coordinate detection. PH→DOMESTIC else ABROAD mapping is in api/v1/registration/location-verify.ts.';
