-- Fix inverted Role column exposure (audit Q7 finding).
--
-- 20260915000001_rls_hardening.sql intended authenticated reads of slug +
-- name only, but the live grants are exactly backwards: authenticated holds
-- SELECT on (permissions, key, is_system, description, createdAt, id) and
-- holds NO grant on slug/name. Effect: every signed-in user can read the
-- RBAC matrix and internal flags, while app role resolution
-- (select slug[,name] on the anon client) is denied and silently falls back
-- to user_metadata/defaults.
--
-- Fix: converge to the intended end state from ANY current state — revoke
-- everything on Role from authenticated, then grant back exactly the two
-- label columns. RLS policy role_read_authenticated (using true) is
-- untouched; anon access is untouched (none); service_role is untouched.
-- No application code change needed: clients already select slug/name.
--
-- Validation (run before/after apply; after must be empty = PASS):
--   select grantee, table_name, column_name, privilege_type
--   from information_schema.role_column_grants
--   where grantee = 'authenticated' and table_name = 'Role'
--     and privilege_type = 'SELECT'
--     and column_name not in ('slug', 'name');
-- Idempotent (REVOKE/GRANT re-runs are safe).
-- Down (rollback only — restores the over-exposed state, never ship outside
-- an approved rollback window):
--   grant select (permissions, key, is_system, description, "createdAt", id)
--     on "Role" to authenticated;
--   revoke select (slug, name) on "Role" from authenticated;

revoke all on "Role" from authenticated;
grant select (slug, name) on "Role" to authenticated;
